version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/DbLocator"
    schedule:
      interval: "monthly"
      day: "monday" 
      time: "08:00"
      timezone: "America/Chicago"

  - package-ecosystem: "nuget"
    directory: "/DbLocatorTests"
    schedule:
      interval: "monthly"
      day: "monday" 
      time: "08:00"
      timezone: "America/Chicago"

