name: "Deploy Nuget"

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches: [ "master" ]

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 9.0.x
            - name: Restore dependencies
              run: dotnet restore
            - name: Build
              run: dotnet build --no-restore

    deploy:
        needs: build
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'

        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v3.1.1
              with:
                  versionSpec: '6.0.x'

            - name: Determine Version
              id: gitversion
              uses: gittools/actions/gitversion/execute@v3.1.1
              with:
                  useConfigFile: true

            - name: Download dotnet
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 9.0.x

            - name: Restore dependencies
              run: dotnet restore

            - name: Build project
              run: dotnet build --configuration Release

            - name: Pack NuGet package
              run: dotnet pack --configuration Release /p:PackageVersion=${{ steps.gitversion.outputs.semVer }}

            - name: Push to GitHub
              run: dotnet nuget push DbLocator/bin/Release/*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.PAT }} --skip-duplicate

            - name: Publish to NuGet
              run: dotnet nuget push DbLocator/bin/Release/*.nupkg --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_KEY }} --skip-duplicate
