name: "Deploy Nuget"

on:
  workflow_dispatch:
  release:
    types: [published]

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 9.0.x
            - name: Restore dependencies
              run: dotnet restore
            - name: Build
              run: dotnet build --no-restore
    deploy:
      needs: build
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'

      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 9.0.x

        - name: Extract version from tag
          id: extract_version
          run: |
            TAG=${GITHUB_REF##*/}
            VERSION=${TAG#v}
            echo "Using tag $TAG -> version $VERSION"
            echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

        - name: Restore dependencies
          run: dotnet restore

        - name: Build project
          run: dotnet build --configuration Release

        - name: Pack NuGet package
          run: dotnet pack --configuration Release /p:PackageVersion=${{ steps.extract_version.outputs.VERSION }}

        - name: Publish to NuGet
          run: dotnet nuget push DbLocator/bin/Release/*.nupkg --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_KEY }} --skip-duplicate
